# Generated by Django 5.0.6 on 2024-05-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_article_alter_about_about_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=17)),
                ('mail', models.CharField(max_length=30)),
                ('work_type', models.CharField(max_length=50)),
            ],
        ),
    ]
