# Generated by Django 5.0.6 on 2024-05-18 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_review_alter_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_date',
            field=models.DateField(default=None),
        ),
    ]
