# Generated by Django 5.0.6 on 2024-05-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_review_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(default='https://smaller-pictures.appspot.com/images/dreamstime_xxl_65780868_small.jpg', max_length=500),
        ),
        migrations.AddField(
            model_name='contact',
            name='image_url',
            field=models.CharField(default='https://devscience.by/assets/img/team/team-3.jpg', max_length=500),
        ),
    ]
