# Generated by Django 5.0.6 on 2024-05-19 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_article_image_url_contact_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='myapp.doctor'),
        ),
        migrations.AddField(
            model_name='service',
            name='clients',
            field=models.ManyToManyField(through='myapp.Sale', to='myapp.client'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='myapp.category'),
        ),
    ]
