# Generated by Django 5.0.6 on 2024-05-19 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_client_doctor_service_clients_alter_doctor_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contact'),
        ),
        migrations.AlterField(
            model_name='plannedvisit',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.contact'),
        ),
        migrations.AlterField(
            model_name='client',
            name='doctor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client', to='myapp.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='myapp.category'),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
