# Generated by Django 5.0.6 on 2024-09-24 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_sale_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='client',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='services',
        ),
        migrations.AddField(
            model_name='sale',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale', to='myapp.cart'),
        ),
    ]
