# Generated by Django 5.0.6 on 2024-09-24 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_cart_client_remove_cart_services_sale_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity',
        ),
        migrations.AddField(
            model_name='cart',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.client'),
        ),
        migrations.AddField(
            model_name='cart',
            name='services',
            field=models.ManyToManyField(to='myapp.service'),
        ),
    ]
