# Generated by Django 5.0.6 on 2024-09-24 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_sale_cart_remove_sale_quantity_cart_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=12)),
                ('registry_number', models.CharField(max_length=4)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='about',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='logo',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='about',
            name='certificate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.certificate'),
        ),
    ]
