# Generated by Django 5.0.6 on 2024-09-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_certificate_about_details_about_history_about_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='phone',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='website_url',
            field=models.URLField(null=True),
        ),
    ]
